# Vehicle Detection System - Default Configuration

# Detection settings
detection:
  model_path: "models/yolov5n-416.xml"
  device: "CPU"  # CPU or GPU
  input_shape: [416, 416]
  conf_threshold: 0.25
  nms_threshold: 0.5
  frame_skip: 2

# UI settings
ui:
  window_width: 1200
  window_height: 800
  theme: "dark"
  auto_save: true

# Storage settings
storage:
  enabled: true
  save_interval: 300  # seconds
  output_dir: "data/counts"
  format: "json"  # json, csv, both

# Advanced settings
advanced:
  max_fps: 30
  buffer_size: 1
  log_level: "INFO"
  enable_tracking: true
  trail_length: 30
