detection:
  conf_threshold: 0.25
  device: GPU
  frame_skip: 10
  input_shape:
  - 416
  - 416
  model_path: models/yolov5n-416.xml
  nms_threshold: 0.5
storage:
  enabled: true
  format: json
  output_dir: data/counts
  save_interval: 300
ui:
  auto_save: true
  theme: dark
  window_height: 800
  window_width: 1200
