# Development Configuration - Optimized for testing

detection:
  model_path: "models/yolov5n-416.xml"
  device: "CPU"
  input_shape: [320, 320]  # Smaller for faster testing
  conf_threshold: 0.3
  nms_threshold: 0.5
  frame_skip: 3  # Skip more frames for faster processing

ui:
  window_width: 1000
  window_height: 700
  theme: "dark"
  auto_save: false

storage:
  enabled: false  # Disable storage in development
  save_interval: 60
  output_dir: "data/dev"
  format: "json"

advanced:
  max_fps: 15  # Lower FPS for development
  log_level: "DEBUG"
  enable_tracking: true
