# Production Configuration - Optimized for deployment

detection:
  model_path: "models/yolov5n-416.xml"
  device: "GPU"  # Use GPU in production
  input_shape: [416, 416]
  conf_threshold: 0.25
  nms_threshold: 0.5
  frame_skip: 1  # Process all frames

ui:
  window_width: 1400
  window_height: 900
  theme: "dark"
  auto_save: true

storage:
  enabled: true
  save_interval: 300
  output_dir: "/var/log/vehicle-detection"
  format: "both"  # Save as both JSON and CSV

advanced:
  max_fps: 30
  log_level: "INFO"
  enable_tracking: true
